### PR TITLE
Do not enable Memory and PCI UI patching on real Macs

### PR DESCRIPTION
**Pull request by PMheart**
Closes https://github.com/acidanthera/bugtracker/issues/2046

### CODE REVIEW

**Comment by khronokernel** [comment]
With MacPro5,1 units spoofing to a MacPro7,1 SMBIOS, might still be recommended to allow the option to disable the memory and PCIe patching. For `auto`, I believe your current implementation is fine but for users would configure it may be ideal to allow them to configure as desired instead of locking it outright

**Comment by PMheart** [comment]
Will MP51->MP71 be some kind of exception? And sure, I will just turn on the patches for `auto`.

**Comment by khronokernel** [comment]
> Will MP51->MP71 be some kind of exception?

This would be applicable for any Mac that spoofs to MacPro7,1, MacPro5,1 would just be a common group. Mac minis, Xserves, etc may also wish to spoof. So I'd recommend just allowing any model to use the patches so long as the user has opt'd in

**Comment by PMheart** [comment]
Hmm, OK. Then shall we instead notify the user to manually disable the patch where causing problems instead?

**Comment by khronokernel** [comment]
> Then shall we instead notify the user to manually disable the patch where causing problems instead?

Reasonable, but under what circumstances? The initial issue filed applies to every machine, this is the danger of hooking `_cs_validate_page`. Slower hardware is affected much more heavily, so this can happen on hackintoshes as well

**Pull request merged**
